language: node_js
node_js:
  - 12
dist: trusty
sudo: required
addons:
  chrome: stable
  hostname: localhost
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - npm run start &
services:
  - mongodb
  - redis-server
env:
  global:
    - NODE_ENV=ci
    - PORT=3000
    - GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}
    - GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}
    - MONGO_URI="mongodb://127.0.0.1:27017/blog_ci"
    - COOKIE_KEY="123123123"
    - REDIS_URL="redis://127.0.0.1:6379"
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
